services:
  ros_humble:
    build:
      context: .
      args:
        USER_NAME: ${USER_NAME}
        USER_ID: ${USER_ID}
        USER_GID: ${USER_GID}
    image: ros_template:humble
    container_name: ros_humble_dev
    hostname: ros-humble-dev
    env_file:
      - .env
    volumes:
      - .:/app
    group_add:
      - dialout
      - sudo
    stdin_open: true
    tty: true
